# Generated by Django 2.0.5 on 2018-06-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180604_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='内容',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='标题',
            new_name='title',
        ),
    ]
