# Generated by Django 2.0.5 on 2018-07-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likerecord',
            name='liked_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
