# Generated by Django 2.0.5 on 2018-06-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='suthor',
            new_name='author',
        ),
    ]
